# Generated by Django 3.2 on 2022-02-11 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('booked_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.bookinginfo')),
            ],
        ),
    ]
