# Generated by Django 3.2 on 2022-02-12 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_bookedlisting_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedlisting',
            name='price',
        ),
        migrations.AlterField(
            model_name='bookedlisting',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='listings.bookinginfo'),
        ),
    ]
