# Generated by Django 3.2 on 2022-02-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20220212_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedlisting',
            old_name='listing',
            new_name='booking_info',
        ),
    ]
