# Generated by Django 3.2 on 2022-02-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_bookinginfo_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='booked',
        ),
    ]
